packages:
  - '.'
extra-deps:
  - git: https://github.com/poor-a/ActiveHs-misc.git
    commit: 9ec93e61f04a90592f3915e949040a815e481684
    subdirs:
      - activehs-base
      - data-pprint
      - dia-base
      - dia-functions
  - snap-1.0.0.2
  - heist-1.0.1.1
  - map-syntax-0.2.0.2
resolver: lts-12.1
