#!/bin/sh

# Convenience script for building ActiveHs

ACTIVEHS_SRC="/development/activehs"
STACK_WORK="${ACTIVEHS_SRC}/.stack-work"

if [ -d $STACK_WORK -o -L $STACK_WORK ]; then
    stack --stack-yaml "${ACTIVEHS_SRC}/stack.yaml" build --fast
else
    echo "Directory or link ${STACK_WORK} is not found in ${ACTIVEHS_SRC}."
    exit 1
fi
