#!/bin/sh

# Convenience script for running ActiveHs

STACK_WORK=".stack-work"
ACTIVEHS_SRC="/development/activehs"
INIT="/development/init"

if [ ! \( -d "$ACTIVEHS_SRC/$STACK_WORK" -o -L "$ACTIVEHS_SRC/$STACK_WORK" \) ]; then
    echo "Creating link to $INIT/$STACK_WORK in $ACTIVEHS_SRC."
    ln -s "$INIT/$STACK_WORK" "$ACTIVEHS_SRC/"
fi

stack --stack-yaml "${ACTIVEHS_SRC}/stack.yaml" exec activehs -- $@
